# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Deploy-Agent-Pipeline

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- name: AzureSubscription
  value: BuildAgentSP

steps:
- task: AzureCLI@2
  displayName: "Build Custom Image"
  inputs:
    azureSubscription: $(AzureSubscription)
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    arguments: '$(Location) $(ResourceGroup) $(ScaleSetName) $(VMUserName) $(FileName) $(AgentPoolName) $(AzureDevOpsPAT) $(AzureDevOpsURL)'
    scriptPath: './deploy-agent.sh'